# Generated by Django 3.1.3 on 2021-01-11 06:17

from django.db import migrations, models
import django.db.models.deletion
import item.models.items


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
                ('item_img', models.ImageField(blank=True, null=True, upload_to=item.models.items.load_path)),
                ('item_detail', models.TextField(blank=True, null=True)),
                ('item_price', models.IntegerField(default=0)),
                ('item_total', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('store_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='store.store')),
            ],
        ),
    ]
