# Generated by Django 3.1.2 on 2020-10-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customtoken', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtoken',
            name='key',
            field=models.CharField(max_length=64),
        ),
    ]
