# Generated by Django 3.0.8 on 2020-08-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=30)),
                ('store_email', models.EmailField(max_length=254, unique=True)),
                ('store_password', models.CharField(max_length=30)),
                ('withdrawal_datetime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
