# Generated by Django 3.1 on 2020-08-23 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200815_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_email',
            field=models.EmailField(max_length=254),
        ),
    ]
