# Generated by Django 3.0.8 on 2020-08-05 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_totalprice', models.IntegerField(default=0)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('withdrawal_datetime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_quantity', models.IntegerField(default=0)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.Item')),
                ('pay_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.Payment')),
            ],
        ),
    ]
