# Generated by Django 3.1.3 on 2021-01-11 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_totalprice', models.IntegerField(default=0)),
                ('user_email', models.EmailField(max_length=254)),
                ('bought_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_quantity', models.IntegerField(default=0)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.item')),
                ('pay_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.payment')),
            ],
        ),
    ]
