# Generated by Django 3.1 on 2020-08-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='withdrawal_datetime',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='DeleteDate'),
        ),
    ]
