# Generated by Django 3.1 on 2020-09-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200823_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='withdrawal_datetime',
        ),
        migrations.AddField(
            model_name='user',
            name='withdrawal_at',
            field=models.DateTimeField(null=True),
        ),
    ]
